title: Fcuk yeah 
author: GitHub User
email: firsttime@domain.com
description: > 
 We do what we want, when we want 

# social links
twitter_username: me 
github_username:  you

show_excerpts: true

theme: minima
